# Generated by Django 5.2.5 on 2025-09-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendationlog',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='recommended_items',
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='recommendations',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='source',
            field=models.CharField(choices=[('ml', 'ML'), ('cooccurrence', 'Co-occurrence'), ('popular', 'Popular'), ('cold_start', 'Cold Start')], default='cold_start', max_length=32),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
